# Generated by Django 4.2.7 on 2023-11-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('requirements', models.TextField(max_length=1000)),
                ('contact', models.CharField(max_length=100)),
                ('link_google_form', models.URLField(default=False)),
            ],
        ),
    ]
