# Generated by Django 4.2.7 on 2023-11-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='link_google_form',
        ),
    ]
